#!/usr/bin/python3
# author Sean Hellum
"""Mathlang compiler."""
import fire
import math

def compile(file):
    theFile = open(file, 'r')
    if theFile.mode == 'r':
        f = open(file, "r")
        f = f.readlines()
        count = 0
        for line in f:
            try:
                if line[:4] == "sqrt":
                    print(math.sqrt(float(line[4:])))
                    continue
                print(eval(line))
                count += 1
            except:
                print(f"Syntax Error on line {count+1}")


if __name__ == '__main__':
    fire.Fire()
