#!/usr/bin/python3
import fire

def interpreter(file):
    theFile = open(file,'r')
    if theFile.mode == 'r':
        f = open(file, "r")
        f = f.readlines()
        count = 0
        for line in f:
            try:
                print(eval(line))
                count+=1
            except:
                print(f"Syntax Error on line {count+1}")
if __name__ == '__main__':
    fire.Fire(interpreter)
